# Test data preprocessing loading

In [4]:
from myCode import myDataLoader

from torch.utils.data import Dataset
import numpy as np
import glob
from fastai.vision import *

In [5]:
class CMRIreconDataset(Dataset):
    """CMRIrecon dataset."""
    def __init__(self, root_dir):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.root_dir = root_dir
        self.input_file_list  = glob.glob(root_dir + "/*RADIAL*.mat")
        self.target_file_list = glob.glob(root_dir + "/*CARTESIAN*.mat")
        self.c = 20

    def __len__(self):
#         print("print length of inputs",len(self.inputs))
#         print("print shape of inputs",np.shape(self.inputs))
        return len(self.input_file_list)
        print(len(self.input_file_list))

    def __getitem__(self, idx):

        X = np.load(self.input_file_list[idx])
        Y = np.load(self.target_file_list[idx])
        return  X, Y


In [6]:

train_dataset = myDataLoader.CMRIreconDataset(
'C:/Users/littl/Documents/PythonScripts/newMRIrecon/data/processed_data/96x96_cropped_data/train')
valid_dataset = myDataLoader.CMRIreconDataset(
'C:/Users/littl/Documents/PythonScripts/newMRIrecon/data/processed_data/96x96_cropped_data/train')

# train_dataset = myDataLoader.CMRIreconDataset("data/processed_data/96x96_cropped_data/train")
# valid_dataset = myDataLoader.CMRIreconDataset("data/processed_data/96x96_cropped_data/valid")

print(type(train_dataset))
print(type(valid_dataset))


<class 'myCode.myDataLoader.CMRIreconDataset'>
<class 'myCode.myDataLoader.CMRIreconDataset'>


In [35]:
root_dir = ('C:/Users/littl/Documents/PythonScripts/newMRIrecon/data/processed_data/96x96_cropped_data/train/')

input_file_list  = glob.glob(root_dir + "*CARTESIAN*")


In [36]:
print(len(input_file_list))

518


In [55]:
idx = 2

X = np.load(input_file_list[idx])

print(X.files)
print(X['arr_0'])
arr = X.files['arr_0']
print(arr)

['arr_0']
[[[-0.785327 -0.627362 -0.51825  -0.832413 ... -0.734896 -0.206279 -0.67063  -0.643855]
  [-0.540899 -0.683268 -0.280725 -0.387983 ... -0.693662 -0.151477 -0.375176 -0.729999]
  [-0.669993 -0.6704   -0.60052  -0.807805 ... -0.671999 -0.145361 -0.430981 -0.554392]
  [-0.679773 -0.651656 -0.611777 -0.633182 ... -0.685406 -0.82867  -0.641102 -0.489029]
  ...
  [ 3.368392  1.92659   0.939045 -0.258209 ... -0.78856  -0.466699 -0.677366 -0.737913]
  [ 3.217816  2.525179  1.587209 -0.738721 ... -0.710827 -0.824375 -0.616917 -0.731211]
  [ 2.480535  2.999264  3.178148 -0.364991 ... -0.808231 -0.664005 -0.388041 -0.68014 ]
  [ 3.292205  2.470645  3.567294  0.395345 ... -0.82138  -0.731198 -0.578512 -0.619698]]

 [[-0.812715 -0.573618 -0.58708  -0.564575 ... -0.673695 -0.077262 -0.220015 -0.647177]
  [-0.569802 -0.565443 -0.829861 -0.583003 ... -0.778844 -0.089058 -0.066327 -0.793788]
  [-0.577474 -0.532831 -0.720879 -0.757272 ... -0.614898 -0.556815 -0.404404 -0.557222]
  [-0.6656   -

TypeError: list indices must be integers or slices, not str

0
